server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~ \.mjs$ {
        types { }
        default_type text/javascript;
    }

    location ~* \.html$ {
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|mjs|css)$ {
        add_header Cache-Control "public, max-age=86400";
    }
}
